declare module "bun" {
	interface Env {
		CONFIGURATION_URL: string;
		CONFIGURATION_POLL_ENABLED: string;
		CONFIGURATION_POLL_INTERVAL: string;
	}
}

const CONFIGURATION_URL = process.env.CONFIGURATION_URL;
const CONFIGURATION_POLL_ENABLED =
	process.env.CONFIGURATION_POLL_ENABLED === "true";
const CONFIGURATION_POLL_INTERVAL = Number.parseInt(
	process.env.CONFIGURATION_POLL_INTERVAL || "30000",
	10,
);

export {
	CONFIGURATION_URL,
	CONFIGURATION_POLL_ENABLED,
	CONFIGURATION_POLL_INTERVAL,
};
